version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: python src/data_collection/ingest_population_data.py